# Generated by Django 5.0 on 2023-12-04 18:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cards_desc_alter_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='desc',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Название'),
        ),
    ]
