# Generated by Django 5.0 on 2023-12-05 13:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='desc_main',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=200, verbose_name='Название'),
        ),
    ]
