# Generated by Django 5.0 on 2023-12-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cards_desc_alter_cards_desc_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='size_warning',
            field=models.CharField(blank=True, default='Внимание! Если размер файла привышает 500кб, то загрузка сайта будет снижена!', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.cards'),
        ),
    ]
