# Generated by Django 5.0 on 2023-12-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_gallery_i_agree_alter_cards_size_warning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='size_warning',
        ),
    ]
